### ISSUE TITLE
Unable to write private key after the reset button was pressed during partition formatting procedure

### ISSUE THREAD

**Issue by mc-ff** [astarte-platform/astarte-device-sdk-esp32#113]
On IDF 5, first call ensure_mounted function returns :

E (1198) ASTARTE_CREDENTIALS: Cannot create /astarte/ast_cred directory
E (1293) ASTARTE_CREDENTIALS: Cannot open /astarte/ast_cred/device.key for writing
E (1293) ASTARTE_CREDENTIALS: Cannot store private

mkdir returns FR_DENIED

**Comment by mc-ff** [comment]
The problem is present on our code.
I'm porting my older project (based on IDF 3.3 and Astarte SDK 0.11.2) to the new IDF and latest stable Astarte SDK. 
To develop the project i am using a ESP32-S3 DevKitC-1
ESP-IDF is v 5.0.1 (latest stable version)

Here is my partitions.csv : 

_nvs,      data, nvs,       0x9000,    0x5000,
otadata,  data, ota,       0xe000,    0x2000,
ota_0,    app,  ota_0,     0x10000,   1536K,
ota_1,    app,  ota_1,     0x190000,  1536K,
astarte,  data, fat,       ,          0x20000,
ota_fmr,  data, fat,       ,          0x64000,
nvs_key,  data, nvs_keys,  ,          0x1000_

i'm going to test if the problem is present even in the toggler_led example

**Comment by mc-ff** [comment]
Led example works if we completely erase the flash before writing the new fw. There seems to be some strange behavior in the esp-idf. It can mount the partition but it can't write the directory.

**Comment by harlem88** [comment]
To reproduce the issue press `reset button`  during `Formatting FATFS partition` procedure.
```
W (18785) vfs_fat_spiflash: f_mount failed (13)
I (18785) vfs_fat_spiflash: Formatting FATFS partition, allocation unit size=4096
I (19175) vfs_fat_spiflash: Mounting again
```
after the reboot the device always reboot on this error: 
```
E (3995) ASTARTE_CREDENTIALS: Cannot create /astarte/ast_cred directory
I (4015) ASTARTE_CREDENTIALS: Initializing entropy
I (4015) ASTARTE_CREDENTIALS: Generating the EC key (using curve secp256r1)
I (4235) ASTARTE_CREDENTIALS: Key succesfully generated
E (4245) ASTARTE_CREDENTIALS: Cannot open /astarte/ast_cred/device.key for writing
E (4245) ASTARTE_CREDENTIALS: Cannot store private
E (4255) ASTARTE_EXAMPLE_TOGGLE_LED: Failed to initialize credentials
E (4255) FreeRTOS: FreeRTOS Task "astarte_example" should not return, Aborting now!
```

**Comment by harlem88** [comment]
It is easier to reproduce with these options:
```
#
# Wear Levelling
#
CONFIG_WL_SECTOR_SIZE_512=y
CONFIG_WL_SECTOR_SIZE=512
CONFIG_WL_SECTOR_MODE_SAFE=y
CONFIG_WL_SECTOR_MODE=1
```
- press reset button during formatting procedure:
```
W (4181) vfs_fat_spiflash: f_mount failed (13)
I (4181) vfs_fat_spiflash: Formatting FATFS partition, allocation unit size=512
ets Jul 29 2019 12:21:46
```
- infinite reboot
```
I (4321) ASTARTE_CREDENTIALS: stat directory
I (4461) ASTARTE_CREDENTIALS: Directory /astarte/ast_cred doesn't exist, creating it
E (7941) ASTARTE_CREDENTIALS: Cannot create /astarte/ast_cred directory
I (8421) ASTARTE_CREDENTIALS: Initializing entropy
I (8421) ASTARTE_CREDENTIALS: Generating the EC key (using curve secp256r1)
I (8811) ASTARTE_CREDENTIALS: Key succesfully generated
E (8961) ASTARTE_CREDENTIALS: Cannot open /astarte/ast_cred/device.key for writing
E (8961) ASTARTE_CREDENTIALS: Cannot store private
E (8971) ASTARTE_EXAMPLE_TOGGLE_LED: Failed to initialize credentials
E (8971) FreeRTOS: FreeRTOS Task "astarte_example" should not return, Aborting now!
```

**Comment by harlem88** [comment]
#157
