### ISSUE TITLE
Publish astarte-device-sdk-esp32 to ESP-IDF component registry

### ISSUE THREAD

**Issue by harlem88** [astarte-platform/astarte-device-sdk-esp32#165]
- [publish component docs](https://docs.espressif.com/projects/idf-component-manager/en/latest/guides/packaging_components.html#publish-the-component)
- [upload-components-ci-action](https://github.com/espressif/upload-components-ci-action)

https://components.espressif.com/

**Comment by sorru94** [comment]
The component has been published manually at `v1.3.1`. Pubblishing of version `v1.3.2`  will be automated in CI.
See the [component on the registry](https://components.espressif.com/components/astarte-platform/astarte-device-sdk-esp32).
