### ISSUE TITLE
Build error: enumeration value 'MQTT_EVENT_BEFORE_CONNECT' not handled in switch [-Werror=switch]

### ISSUE THREAD

**Issue by sanjumn** [astarte-platform/astarte-device-sdk-esp32#2]
Hi,

Tried to build astarte-device-sdk-esp32 (master branch) SDK's 'toggle_led' example but the build system throws following error:
............................................................................................................................
astarte-device-sdk-esp32/astarte_device.c:554:5: error: enumeration value 'MQTT_EVENT_BEFORE_CONNECT' not handled in switch [-Werror=switch]
     switch (event->event_id) {
     ^
cc1: some warnings being treated as errors
............................................................................................................................

Later, I tried to build the example from v0.10.0-rc.0 of the SDK but it results in the same error as above (after execution of 'make'). Please note that both the 'master' and 'v0.10.0-rc.0' versions of the SDK were built with the latest 'esp-idf'

Does the SDK example needs to be built with any specific snapshot of esp-idf? Please advice!

Thanks,
Sanju

**Comment by sanjumn** [comment]
Hi,

The said error (warning treated as error) can be resolved by adding a switch case statement for MQTT_EVENT_BEFORE_CONNECT at line no.555 of file, 'astarte_device.c' as follows:
...........................................................................................................................................
static esp_err_t mqtt_event_handler(esp_mqtt_event_handle_t event)
{
    astarte_device_handle_t device = (astarte_device_handle_t) event->user_context;
    switch (event->event_id) {
        case MQTT_EVENT_BEFORE_CONNECT: //SN_a
            ESP_LOGI(TAG, "MQTT_EVENT_BEFORE_CONNECT");
            break;
            :
            :
}
...........................................................................................................................................

Regards,
Sanjumn

**Comment by bettio** [comment]
Thanks for reporting the issue, we fixed the issue: https://github.com/astarte-platform/astarte-device-sdk-esp32/commit/dcf52717a5368d3aef062e0743d5f66c20f80393

Let us know if you have any other issue or question :)
