### ISSUE TITLE
Ensure that the SDK returns meaningful error codes upon Pairing and connection

### ISSUE THREAD

**Issue by drf** [astarte-platform/astarte-device-sdk-esp32#28]
The SDK should return meaningful errors upon specific errors on the Astarte wire. Currently, a generic ASTARTE_ERR is returned, but more details should be given when possible (e.g.: something like ASTARTE_BAD_CREDENTIALS when pairing doesn't succeed with a 401/403)

**Comment by rbino** [comment]
Closed by https://github.com/astarte-platform/astarte-device-sdk-esp32/pull/30
