### ISSUE TITLE
Reinitializing Error, Repeated Restart

### ISSUE THREAD

**Issue by skybosg** [astarte-platform/astarte-device-sdk-esp32#46]
I have been using the astarte-device-sdk-esp32 for about a year now and I just updated to your recent sdk v0.11.4 for my project. There is a reinitialization issue where if the ESP32 loses its wifi signal and then gets it back it will reconnect to the wifi then 'reinitialize' and when it does this it gets stuck in a cycle where it will display 'MQTT_EVENT_CONNECTED' then 'MQTT_EVENT_DISCONNECTED' and will try to reinitialize again after it gets a 'Certificate error, notifying the reinit task' over and over. Once this starts then the device code will do this loop indefinitely until there is a hard reset. 

I saw that in a older code version you had fixed this issue. Is there something that I am missing? If the device receives an MQTT EVENT during reinitialization will that cause it to go into an error state again and again?

Thank you, 

I believe that I may have found the issue in my code. I will update you about this when I test some things out. 

Thank you

**Comment by rbino** [comment]
Hi @skybosg, do you have a way to reproduce the issue and/or some logs to share?
Feel free to write where you think the issue could be in the code.

**Comment by skybosg** [comment]
rbino, 

The ESP32 shows the 'Device topic is: <realm/DeviceID>'. Then the below log outputs. When it gets to 'Failed to init astarte device' then it tries all over again with the 'hwid', 'credentials_secret', 'key' and 'certificate'.

E (75388852) esp-tls-mbedtls: mbedtls_ssl_setup returned -0x7f00
E (75388852) esp-tls: create_ssl_handle failed
E (75388862) esp-tls: Failed to open new connection
E (75388862) TRANS_SSL: Failed to open a new connection
E (75388872) HTTP_CLIENT: Connection failed, sock < 0
E (75388872) ASTARTE_PAIRING: HTTP GET request failed: ESP_ERR_HTTP_CONNECT
E (75388872) ASTARTE_DEVICE: Error in get_mqtt_v1_broker_url
E (75388882) ASTARTE_DEVICE: Cannot init Astarte device: 9
E (75388892) ASTARTE: Failed to init astarte device

The device connects initially after flashing the chip just fine and will most likely work on a reboot. But this will loop sometimes after a day or an hour. It is random. I am looking into the code now.

**Comment by bettio** [comment]
@skybosg did you try v1.0 branch / release? does it work for you now?
