### ISSUE TITLE
Maximum header size for JWT in Astarte device register

### ISSUE THREAD

**Issue by harlem88** [astarte-platform/astarte-device-sdk-esp32#93]
The maximum length of JWT used in HTTP Header for registering a device is `1024`, It is defined as constant here:
https://github.com/astarte-platform/astarte-device-sdk-esp32/blob/eeda3410800198bec6f34b288415be4e649c5b53/astarte_pairing.c#L21 

At this time, if you have generated, for example a `pairing_token` greater than `1024`, it will be truncated causing the device registration to fail.
This can be occurred when a `JWT` was generated from `RSA` key.

**Comment by samubd** [comment]
I had this issue too using Keycloak for generating JWT tokens.
https://www.keycloak.org/
