### ISSUE TITLE
Add support for ESP-IDF v5.0

### ISSUE THREAD

**Issue by harlem88** [astarte-platform/astarte-device-sdk-esp32#98]
Missing support for newer version of the IDF 5.0.

**Comment by sorru94** [comment]
In the [guide](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/migration-guides/release-5.x/gcc.html) for the migration from IDF 4.x to 5.x.
Suggest the use of `<inttypes.h>` to facilitate the [changes](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/migration-guides/release-5.x/gcc.html) regarding the size of integers of this new version.
